### ISSUE TITLE
米游社每日任务成功但是米游社游戏签到失败

### ISSUE THREAD

**Issue by yihuanlin** [starudream/miyoushe-task#2]
好像是https握手失败

> [cmd/main.go:8] exit: 1, error: get stoken error: [miyoushe] response status: , error: execute error: Post "https://api-takumi.mihoyo.com/account/ma-cn-session/app/getTokenByGameToken": net/http: TLS handshake timeout

另外请问有意向加入自动签到后向[Discord Webhook](https://discord.com/developers/docs/resources/webhook)发送结果的功能吗
`curl -i --trace-ascii - -X POST https://discord.com/api/webhooks/api地址 "Content-Type:application/json" --data '{"content": "消息内容"}'`

**Comment by starudream** [comment]
> 好像是https握手失败

我刚试了一下还是可以正常请求的，先看一下有没有设置 `https_proxy` 相关代理

> Discord Webhook

```yaml
ntfy:
  webhook:
    url: https://discord.com/api/webhooks/xxx
    method: POST
    type: JSON
    key: content
```

**Comment by yihuanlin** [comment]
感谢，我今天重试也可以正常请求了，不过notify加到app.yaml里也没有自动发送签到结果，但是docker run -it --rm -v $(pwd)/miyoushe:/miyoushe -e DEBUG=true starudream/miyoushe-task /miyoushe-task -c /miyoushe/app.yaml notify send是可以正常发送的。notify是放app.yaml还是docker的compose.yml啊
```
app.ntfy.webhook.key: "content"
app.ntfy.webhook.method: "POST"
app.ntfy.webhook.type: "json"
app.ntfy.webhook.url: "https://discord.com/api/webhooks/..."
```
另外是否考虑给corn运行时增加一个随机的睡眠时间，这样感觉会更难被程序检测到

**Comment by starudream** [comment]
> notify是放app.yaml还是docker的compose.yml啊

有 `app.` 前缀的放在 `docker-compose.yml` 的 `environments` 中，去掉 `app.` 是放在 `app.yaml` 中。

> 更难被程序检测到

目前看米哈游相关开源产品，都会遇到被检测 [极验](http://www.geetest.com) 的问题，添加随机睡眠时间并不能解决该问题

**Comment by yihuanlin** [comment]
感谢，我现在也触发验证码了，但是https://www.rrocr.com我访问不了不知道是不是因为我ip在国外被屏蔽了，浏览器上也打不开

> ERR job/forum.go:121 verify error: dm error: [rrocr] response status: 404 Not Found, error: status: 0, msg: , code: 0

**Comment by starudream** [comment]
打码平台是这个 http://www.rrocr.com，我看这个网站前一阵子说不继续更新了，目前还是可以凑合着用。

**Comment by Henvy-Mango** [comment]
建议notifty的tg通知的api地址 `https://api.telegram.org` 可以自定义，这样可以使用cf反代

**Comment by starudream** [comment]
> 建议notifty的tg通知的api地址 `https://api.telegram.org` 可以自定义，这样可以使用cf反代

暂时可以这样用

```yaml
ntfy:
  webhook:
    url: https://{ADDRESS:-api.telegram.org}/bot{TOKEN}/sendMessage
    method: POST
    type: JSON
    key: text
    extra:
      chat_id: {CHAT_ID}
```
