### ISSUE TITLE
sign game失败

### ISSUE THREAD

**Issue by ZhiyuanEric** [starudream/miyoushe-task#8]
前面的步骤都成功了，sign game失败了，win和docker都试过了是同样的错误代码
`[cmd/main.go:8] exit: 1, error: get stoken error: [miyoushe] response status: 200 OK, error: retcode: -100, message: 登 录状态失效，请重新登录, data: <nil>`

**Comment by starudream** [comment]
是用的扫码登录吗？

检查一下配置文件内是否有 `uid` `gtoken`

**Comment by ZhiyuanEric** [comment]
`accounts:
  - ctoken: ""
    device:
      channel: miyousheluodi
      id: 2fd0b7a3...
      model:....
      name: Xiaomi ...
      type: "2"
      version: "13"
    gtoken: v2_mra8M9rPT...
    mid: ""
    phone: "19531309925"
    sign_game_ids: []
    stoken: ""
    uid: "3916......"
cron:
  spec: 5 4 8 * * *
  startup: false
log:
  console:
    format: text
    level: INFO
  file:
    daily_rotate: true
    enabled: false
    filename: "miyoushe-task_v1.3.2_windows_amd64\\miyoushe-task.log"
    format: text
    level: INFO
    max_backups: 10
    max_size: 100
rrocr:
  key: ""
ttocr:
  interval: 0s
  item_id: ""
  key: ""
  timeout: 0s
`

**Comment by ZhiyuanEric** [comment]
```
accounts:
  - ctoken: ""
    device:
      channel: miyousheluodi
      id: 2f..
      model: ...
      name: Xiaomi...
      type: "2"
      version: "13"
    gtoken: v2_l89f...
    mid: ""
    phone: "1..."
    sign_game_ids: []
    stoken: ""
    uid: "39.."
cron:
  spec: 5 4 8 * * *
  startup: false
log:
  console:
    format: text
    level: INFO
  file:
    daily_rotate: true
    enabled: false
    filename: "..\miyoushe-task_v1.3.2_windows_amd64\\miyoushe-task.log"
    format: text
    level: INFO
    max_backups: 10
    max_size: 100
rrocr:
  key: ""
ttocr:
  interval: 0s
  item_id: ""
  key: ""
  timeout: 0s

```
